### ISSUE TITLE
TBC player question

### ISSUE THREAD

**Issue by leqqq** [nullfoxh/PlateBuffer#1]
hey,I am a wow player. I love play TBC. Someday my friend shows a Image. it is yours platebuffer. when I use it in my tbc client. I doesn`t work. I try to change config.lua Chinese. and Restarted it is all showed "??"

is it can`t use chinese client? 

Look forward to your reply. platebuffer really increase my Game Experience

**Comment by nullfoxh** [comment]
Hi!

Sadly I have no means of maintaining support for the Chinese client.
Instead of editing the config.lua, try typing /pb in the games chat and edit the spell names there!
