### ISSUE TITLE
pfUI suport

### ISSUE THREAD

**Issue by gamer4eg** [nullfoxh/PlateBuffer#3]
add pfUI suport
https://github.com/shagu/pfUI

**Comment by nullfoxh** [comment]
What happens when you use it with pfUI?

**Comment by Lunasoll** [comment]
when used with pfUI nameplates, the debuff icons don't show up.

**Comment by nullfoxh** [comment]
Is this still the case? Pretty sure shagu made a compatibility fix in ShaguPlates at least.

**Comment by Lunasoll** [comment]
> Is this still the case? Pretty sure shagu made a compatibility fix in ShaguPlates at least.

ShaguPlates is already included in pfUI addon and on his website he says not to use ShaguPlates together with pfUI. http://shagu.org/ShaguPlates/

**Comment by nullfoxh** [comment]
Yeah I am aware, but this problem is fixed with ShaguPlates.
Is it not fixed with pfUI?

**Comment by Lunasoll** [comment]
I tried with pfUI and it didn't work. I could disable nameplates module in pfUI and install ShaguPlates seperately. May be that would work.

**Comment by nullfoxh** [comment]
I just downloaded the latest version of pfUI and it works fine with PlateBuffer.
Make sure you have the latest versions of both addons!

**Comment by Lunasoll** [comment]
My bad then, I didn't have latest version. Thanks for the addon! Cheers.
