### ISSUE TITLE
Any chance you could modify this to work with HotS on ally nameplates?

### ISSUE THREAD

**Issue by dinkmaster** [nullfoxh/PlateBuffer#4]
I'd love to be able to see my lifebloom/rejuvenation ticker on an ally's nameplate in BGs and such if possible and its not too much work I'd greatly appreciate it

**Comment by nullfoxh** [comment]
Hey, while this is totally doable, it's not what I originally set out to achieve with the addon.
Currently I'm not actively developing this addon, but this could be something I would add if I returned to TBC. I'll let you know if I do end up implementing this! :)
